"use client";

import './globals.css'
import { Inter, Poppins } from 'next/font/google'
import { ReactLenis, useLenis } from '@studio-freight/react-lenis'

const inter = Inter({ subsets: ['latin'] })
const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets:["latin"]
});

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  const lenis = useLenis(({ scroll }) => {
    // called every scroll
  })
  return (
    <ReactLenis root>
     <html lang="en">
      <body className={poppins.className}>{children}</body>
    </html>
  </ReactLenis>
   
  )
}
